### ISSUE TITLE
is it updated and working?

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/come-ottenere-github-pro-studenti-unict#1]

**Comment by eriol** [comment]
Hello, I did yesterday and the document it's fine up to point 5. Instead of a file upload now they want a snap from the webcam. At first I tried to convert the jpg into a mp4 and use obs to stream it as a webcam but it was too blurry. Also It was clear that it wasn't a snap of the document.

So I just printed it and made a snap with the webcam. I know it's a waste of paper, but it worked. In https://education.github.com/discount_requests/application I already see that my request was approved.

**Comment by Helias** [comment]
> Hello, I did yesterday and the document it's fine up to point 5. Instead of a file upload now they want a snap from the webcam. At first I tried to convert the jpg into a mp4 and use obs to stream it as a webcam but it was too blurry. Also It was clear that it wasn't a snap of the document.
> 
> So I just printed it and made a snap with the webcam. I know it's a waste of paper, but it worked. In [education.github.com/discount_requests/application](https://education.github.com/discount_requests/application) I already see that my request was approved.

you could make a PR to update the README adding these informations ;-)
